In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv(r"/data/notebook_files/animal_category.csv")
df

,Index,Animals,Gender,Homly,Types
0,1,Cat,Male,Yes,A
1,2,Dog,Male,Yes,B
2,3,Mouse,Male,Yes,C
3,4,Mouse,Male,Yes,C
4,5,Dog,Female,Yes,A
5,6,Cat,Female,Yes,B
6,7,Lion,Female,Yes,D
7,8,Goat,Female,Yes,E
8,9,Cat,Female,Yes,A
9,10,Dog,Male,Yes,B
10,11,Dog,Male,Yes,B
11,12,Lion,Male,No,D
12,13,Lion,Male,No,D
13,14,Lion,Male,No,D
14,15,Cat,Female,Yes,A
15,16,Lion,Female,No,D
16,17,Lion,Female,No,D
17,18,Cat,Female,Yes,A
18,19,Goat,Male,No,E
19,20,Goat,Female,No,E
20,21,Goat,Male,No,E
21,22,Goat,Female,No,E
22,23,Lion,Male,No,D
23,24,Lion,Female,No,D
24,25,Lion,Male,No,D
25,26,Lion,Female,No,D
26,27,Dog,Male,Yes,B
27,28,Lion,Female,No,D
28,29,Cat,Male,Yes,A
29,30,Lion,Female,No,D

In [10]:
# Create dummy variables

df_new = pd.get_dummies(df)

df_new_1 = pd.get_dummies (df, drop_first = True)

# we have created dummies for all categorical columns

In [4]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

enc = OneHotEncoder()
enc_df = pd.DataFrame(enc.fit_transform(df.iloc[:,2:]).toarray())
enc_df

,0,1,2,3,4,5,6,7,8
0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
5,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
6,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
7,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
8,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
9,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
10,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
11,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
12,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
13,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
14,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
15,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
16,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
17,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
18,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
19,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
20,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
21,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
22,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
23,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
24,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
25,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
26,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
27,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
28,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
29,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [15]:
from sklearn.preprocessing import LabelEncoder

# creating instance of labelencoder

labelencoder = LabelEncoder()

# Data Split into Input and Output variables

X = df.iloc[:, 0:9]

y = df['Animals']

#y = df.iloc[:, 3:] # Alternative approach

#df.columns
X

,Index,Animals,Gender,Homly,Types
0,1,Cat,Male,Yes,A
1,2,Dog,Male,Yes,B
2,3,Mouse,Male,Yes,C
3,4,Mouse,Male,Yes,C
4,5,Dog,Female,Yes,A
5,6,Cat,Female,Yes,B
6,7,Lion,Female,Yes,D
7,8,Goat,Female,Yes,E
8,9,Cat,Female,Yes,A
9,10,Dog,Male,Yes,B
10,11,Dog,Male,Yes,B
11,12,Lion,Male,No,D
12,13,Lion,Male,No,D
13,14,Lion,Male,No,D
14,15,Cat,Female,Yes,A
15,16,Lion,Female,No,D
16,17,Lion,Female,No,D
17,18,Cat,Female,Yes,A
18,19,Goat,Male,No,E
19,20,Goat,Female,No,E
20,21,Goat,Male,No,E
21,22,Goat,Female,No,E
22,23,Lion,Male,No,D
23,24,Lion,Female,No,D
24,25,Lion,Male,No,D
25,26,Lion,Female,No,D
26,27,Dog,Male,Yes,B
27,28,Lion,Female,No,D
28,29,Cat,Male,Yes,A
29,30,Lion,Female,No,D

In [16]:
from sklearn.preprocessing import LabelEncoder

# creating instance of labelencoder

labelencoder = LabelEncoder()

# Data Split into Input and Output variables

X = df.iloc[:, 0:9]

y = df['Animals']

y = df.iloc[:, 3:] # Alternative approach

#df.columns
y

,Homly,Types
0,Yes,A
1,Yes,B
2,Yes,C
3,Yes,C
4,Yes,A
5,Yes,B
6,Yes,D
7,Yes,E
8,Yes,A
9,Yes,B
10,Yes,B
11,No,D
12,No,D
13,No,D
14,Yes,A
15,No,D
16,No,D
17,Yes,A
18,No,E
19,No,E
20,No,E
21,No,E
22,No,D
23,No,D
24,No,D
25,No,D
26,Yes,B
27,No,D
28,Yes,A
29,No,D

In [13]:
X['Animals']= labelencoder.fit_transform(X['Animals'])
X['Gender'] = labelencoder.fit_transform(X['Gender']) 
X[ 'Homly'] = labelencoder.fit_transform(X['Homly'])
X

,Index,Animals,Gender,Homly,Types
0,1,0,1,1,A
1,2,1,1,1,B
2,3,4,1,1,C
3,4,4,1,1,C
4,5,1,0,1,A
5,6,0,0,1,B
6,7,3,0,1,D
7,8,2,0,1,E
8,9,0,0,1,A
9,10,1,1,1,B
10,11,1,1,1,B
11,12,3,1,0,D
12,13,3,1,0,D
13,14,3,1,0,D
14,15,0,0,1,A
15,16,3,0,0,D
16,17,3,0,0,D
17,18,0,0,1,A
18,19,2,1,0,E
19,20,2,0,0,E
20,21,2,1,0,E
21,22,2,0,0,E
22,23,3,1,0,D
23,24,3,0,0,D
24,25,3,1,0,D
25,26,3,0,0,D
26,27,1,1,1,B
27,28,3,0,0,D
28,29,0,1,1,A
29,30,3,0,0,D